"""Audit trail model."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String
from sqlalchemy.orm import Mapped, mapped_column, validates

from app.common.uuid import new_id
from app.models.base_model import BaseModel
from app.models.uuid import UUIDBinary

_MAX_MESSAGE_LENGTH = 1023


class Audit(BaseModel):
    __tablename__ = 'audit'

    id: Mapped[uuid.UUID] = mapped_column(UUIDBinary, primary_key=True, default=new_id)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now, index=True)
    # None if the entry was generated by the system.
    actor_crsid: Mapped[str | None] = mapped_column(String(15), nullable=True)
    message: Mapped[str] = mapped_column(String(_MAX_MESSAGE_LENGTH), nullable=False)

    @validates('message')
    def _fit_column(self, _key: str, value: str) -> str:
        return value[:_MAX_MESSAGE_LENGTH]
